### ISSUE TITLE
Error trying to run

### ISSUE THREAD

**Issue by wickedxter** [gwangyi/UCraftSim#1]
`UCraftSim.java:14: syntax error, unexpected tCONSTANT
        ScriptingContainer container = new ScriptingContainer();`

trying to execute and get this error.

**Comment by gwangyi** [comment]
It may occurred because this project uses jruby. Adding jruby jar file to classpath can be helpful.

I added IntelliJ IDEA project to this repository. You can run this project with IntelliJ IDEA, I think.
